stages:
  prune:
    cmd: python prune.py

  process:
    matrix:
      dataset: ${dataset_list}

    cmd: python process.py ${item.dataset}
    deps:
    - process.py
    outs:
    - out/${item.dataset}

  downstream:
    cmd: python train.py
    deps:
    - out
